# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d86a2983f4104c75a9495ceb6676a2189e9694479bfec8e7a7cea9277bfb11b9d923253b53135e445cfbfdeb4e363c1ffb8ce96604db015c8d5ac2af04bbd1d2

test:
  secret_key_base: cf9cccb56f96a8d23a04ca298db7b0af716020c525458266f8f9e8bfc9253642d79266ef16593035e4e5602341fdbdc97e49e441ac46f07f443e3a7f2a39cabe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
